name: 'Deploy to AWS s3'
description: 'Deploy site on s3 using docker action'
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
    default: mfp-vasili-bucket
  bucket-region:
    description: 'The region of the s3 bucket'
    required: true
    default: eu-west-1
  dist-folder:
    description: 'The folder containing the default file'
    required: true
outputs:
  website-url:
    description: 'URL of a static website'
runs:
  using: docker
  image: Dockerfile
